const path = require('path');
const fs = require('fs');

// Simulate the VBScript generation
const logPath = 'C:\\Users\\USER\\AppData\\Local\\Temp\\alpha_crm_updater_test.log';
const sourcePath = 'C:\\Users\\USER\\AppData\\Local\\Temp\\ALPHA_CRM_Update_test.asar';
const targetAsarPath = 'C:\\Users\\USER\\AppData\\Local\\Programs\\offline-crm-app\\resources\\app.asar';
const appExePath = 'C:\\Users\\USER\\AppData\\Local\\Programs\\offline-crm-app\\ALPHA 고객관리Tool.exe';
const currentPid = process.pid;

const L = [];
L.push('On Error Resume Next');
L.push('Set fso = CreateObject("Scripting.FileSystemObject")');
L.push('Set wsh = CreateObject("WScript.Shell")');
L.push('');
L.push('Dim logF');
L.push('Set logF = fso.OpenTextFile("' + logPath + '", 2, True)');
L.push('logF.WriteLine "=== ALPHA CRM Update Relayer ==="');
L.push('logF.WriteLine "Started: " & Now()');
L.push('');
L.push('Dim pid : pid = ' + currentPid);
L.push('');
L.push('Dim wc : wc = 0');
L.push('Do');
L.push('  WScript.Sleep 500');
L.push('  wc = wc + 1');
L.push('  Dim pRunning : pRunning = False');
L.push('  Dim colProcs');
L.push('  Set colProcs = GetObject("winmgmts:" & Chr(92) & Chr(92) & "." & Chr(92) & "root" & Chr(92) & "cimv2").ExecQuery("SELECT ProcessId FROM Win32_Process WHERE ProcessId=" & pid)');
L.push('  If Err.Number = 0 Then');
L.push('    If colProcs.Count > 0 Then pRunning = True');
L.push('  End If');
L.push('  Err.Clear');
L.push('  If Not pRunning Then Exit Do');
L.push('  If wc > 40 Then Exit Do');
L.push('Loop');
L.push('');
L.push('WScript.Sleep 2000');
L.push('');

const src = sourcePath.replace(/"/g, '""');
const dst = targetAsarPath.replace(/"/g, '""');
const exe = appExePath.replace(/"/g, '""');

L.push('Dim src : src = "' + src + '"');
L.push('Dim dst : dst = "' + dst + '"');
L.push('Dim exe : exe = "' + exe + '"');
L.push('');
L.push('logF.WriteLine "Source: " & src');
L.push('logF.WriteLine "Target: " & dst');
L.push('logF.WriteLine "AppExe: " & exe');
L.push('logF.WriteLine "Source exists: " & fso.FileExists(src)');
L.push('');
L.push('Dim copied : copied = False');
L.push('Dim ci');
L.push('For ci = 1 To 25');
L.push('  Err.Clear');
L.push('  fso.CopyFile src, dst, True');
L.push('  If Err.Number = 0 Then');
L.push('    copied = True');
L.push('    logF.WriteLine "Copy OK on attempt " & ci');
L.push('    Exit For');
L.push('  Else');
L.push('    logF.WriteLine "Copy attempt " & ci & " error: " & Err.Description');
L.push('    Err.Clear');
L.push('  End If');
L.push('  WScript.Sleep 500');
L.push('Next');
L.push('');
L.push('logF.WriteLine "Copy result: " & copied');
L.push('');
L.push('If fso.FileExists(exe) Then');
L.push('  logF.WriteLine "Starting app..."');
L.push('  wsh.Run """" & exe & """", 1, False');
L.push('  logF.WriteLine "App started"');
L.push('Else');
L.push('  logF.WriteLine "ERROR: exe not found: " & exe');
L.push('End If');
L.push('');
L.push('logF.WriteLine "Finished: " & Now()');
L.push('logF.Close');

const vbsContent = L.join('\r\n');
const outputPath = path.join(__dirname, 'test_updater.vbs');
fs.writeFileSync(outputPath, vbsContent, 'utf8');
console.log('VBS generated at:', outputPath);
console.log('\n--- BEGIN VBS CONTENT ---');
console.log(vbsContent);
console.log('--- END VBS CONTENT ---');
